@startuml
partition Buildtime {
start
- Сканирование классов
- Создание BeanDefinition'ов
- Dependency Injection
- Создание прокси
stop
}
partition Runtime {
start
- Запуск приложения
- Создание bean'ов через конструктор
- Запуск PostConstruct методов
stop
}
@enduml
