@startuml
namespace PostAggregate {
class Post {
	id
	title
	content
}

class Comment {
	content
	post_id
}

class Photo {
	title
	content
	post_id
}

Post *-- Comment: post_id
Post *-- Photo: post_id
}
@enduml
