@startuml
namespace PostAggregate {
class Post {
	id
	title
	content
	author_id
}

class Comment {
	content
	post_id
}

Post *-- Comment: post_id
}
namespace AuthorAggregate {
class Author {
id
first_name
last_name
}

Author o-- Post: author_id
}
@enduml
