CREATE TABLE person (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	first_name varchar(255),
	last_name varchar(255),
	CONSTRAINT pk_person PRIMARY KEY(id)
);

CREATE TABLE post (
	id bigint GENERATED BY DEFAULT AS IDENTITY,
	title varchar(255),
	content varchar(255),
	CONSTRAINT pk_post PRIMARY KEY(id)
);

CREATE TABLE comment (
	content varchar(255),
	post_id bigint,
	CONSTRAINT fk_comment_on_post FOREIGN KEY(post_id) REFERENCES post(id)
);
